version: '3.9'
services:
  user-service:
    build: microservices/user_service

    ports:
      - "8001:8001"
    depends_on:
      - mongodb

  waste-item-service:
    build: microservices/waste_item_service

    ports:
      - "8002:8002"
    depends_on:
      - mongodb

  waste-category-service:
    build: microservices/waste_category_service

    ports:
      - "8003:8003"
    depends_on:
      - mongodb

  challenge-service:
    build: microservices/challenge_service

    ports:
      - "8004:8004"
    depends_on:
      - mongodb


  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: haonngcs220336
      MONGO_INITDB_ROOT_PASSWORD: microservice
    volumes:
      - mongo_data:/data/db
      - ./db_confs/mongod.conf:/etc/mongo/mongod.conf
    command: [ "mongod", "--config", "/etc/mongo/mongod.conf" ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
